### PR TITLE
Better: add instructions to avoid ProGuard warnings on Dimelo Mobile SDK during compilation

### PR DESCRIPTION
**Pull request by DrissTM**
Hi !

This PR's goal is to add instructions in the README on how to avoid ProGuard warnings on the SDK during compilation.

LCL faced this issue and thought that their compilation issue was caused by a conflict between our dependencies and theirs, you can find the related JIRA ticket [here](https://dimelo.atlassian.net/browse/RD-9102).

### CODE REVIEW

**Comment by jarthod** [comment]
:warning:

**Review by jarthod — APPROVED** [review]
Looks good to me, let's wait for @waelbenabdallah's opinion too

**Review by waelba — COMMENTED** [review]
fine with me

**Review by waelba — APPROVED** [review]

**Comment by DrissTM** [comment]
I merged it ;)

**Pull request closed without merging**
